[package]
name = "hugo4os"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["boot"]

[dependencies]
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bootloader = "0.10"
uart_16550 = "0.2"
pic8259 = "0.10"
x86_64 = { version = "0.14", features = ["inline_asm"] }
spin = "0.9"
libm = "0.2"